use_frameworks!

target 'SearchTextField_Example', :exclusive => true do
  pod 'SearchTextField', :path => '../'
end

target 'SearchTextField_Tests', :exclusive => true do
  pod 'SearchTextField', :path => '../'

  
end
