# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SearchTextFieldWithRange' do
  
  pod 'SearchTextField', :git => "https://github.com/schmidt9/SearchTextField.git"

end
